# Generated by Django 5.1.7 on 2025-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.TextField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
                ('casal', models.BooleanField(default=False)),
            ],
        ),
    ]
