# Generated by Django 5.1.7 on 2025-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='casal',
            field=models.CharField(max_length=1),
        ),
    ]
